version: '3.4'

services:
  doris-connector:
    hostname: doris-connector
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Domain=test.se
      - ScieboRds__TokenStorageUrl
      - ScieboRds__ConnectorServiceName=port-doris
      - NextCloud__BaseUrl=http://nextcloud
      - NextCloud__User=datasets
      - NextCloud__Password=NDqXt-pkoZA-5bbgM-WftmY-m75q8
      - ManifestIndex__Url=https://snd-storage-metadata-index-test-snd-dev.apps.k8s.gu.se
      - ManifestIndex__ApiKey=key
      - Logging__LogLevel__Default=Debug
    ports:
      - 8080:80
  nextcloud:
    image: nextcloud
    hostname: nextcloud
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    ports:
      - 8081:80