version: '3.4'

services:
  doris-connector:
    hostname: doris-connector
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Domain=test.se
      - PublicFileUrlPrefix=http://example.se/download/
      - ScieboRds__TokenStorageUrl
      - ScieboRds__ConnectorServiceName=port-doris
      - S3__Url=minio:9000
      - S3__AccessKey=user1
      - S3__SecretKey=user1password
      - NextCloud__WebDavBaseUrl=http://nextcloud/remote.php/dav/files/datasets/
      - NextCloud__User=datasets
      - NextCloud__Password=NDqXt-pkoZA-5bbgM-WftmY-m75q8
      - ManifestIndex__Url=https://snd-storage-metadata-index-test-snd-dev.apps.k8s.gu.se
      - ManifestIndex__ApiKey=key
      - Logging__LogLevel__Default=Debug
    ports:
      - 8080:80
  nextcloud:
    image: nextcloud
    hostname: nextcloud
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    ports:
      - 8081:80
  minios3test:
    image: quay.io/minio/minio
    hostname: minio
    command: server --console-address ":9001" /data
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3