services:
  doris-connector:
    hostname: doris-connector
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ScieboRds__RegisterConnectorOnStartup=false
      - ScieboRds__TokenStorageUrl=http://localhost/dummy
      - ScieboRds__ConnectorServiceName=port-doris
      - NextCloud__BaseUrl=http://nextcloud
      - NextCloud__User=datasets
      - NextCloud__Password=datasets123
      - Doris__DorisApiEnabled=false
      - Doris__PrincipalDomain=test.se
      - Doris__ApiUrl=https://dummy.se
      - Doris__ApiKey=key
      - Logging__LogLevel__Default=Debug
    ports:
      - 8080:8080
  nextcloud:
    image: nextcloud
    hostname: nextcloud
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    ports:
      - 8081:80