apiVersion: v1
kind: ConfigMap
metadata:
  name: portdataverseconfig
  namespace: {{ .Release.Namespace  }}
data:
  DATAVERSE_OAUTH_CLIENT_ID: {{ .Values.environment.OAUTH_CLIENT_ID | quote }}
  DATAVERSE_ADDRESS: {{ .Values.environment.ADDRESS | quote }}
  DATAVERSE_API_ADDRESS: {{ .Values.environment.API_ADDRESS | quote }}
  DATAVERSE_OAUTH_CLIENT_SECRET: {{ .Values.environment.OAUTH_CLIENT_SECRET | quote }}