apiVersion: v1
kind: ConfigMap
metadata:
  name: portfigshareconfig
  namespace: {{ .Release.Namespace  }}
data:
  FIGSHARE_OAUTH_CLIENT_ID: {{ .Values.environment.OAUTH_CLIENT_ID | quote }}
  FIGSHARE_ADDRESS: {{ .Values.environment.ADDRESS | quote }}
  FIGSHARE_API_ADDRESS: {{ .Values.environment.API_ADDRESS | quote }}
  FIGSHARE_OAUTH_CLIENT_SECRET: {{ .Values.environment.OAUTH_CLIENT_SECRET | quote }}